version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    # runtime-versions:
      # nodejs: 14.15
      # name: version
    commands:
      - cd angular-11-client && npm install
      - npm install -g @angular/cli
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - ng build --configuration production
      # - command
  post_build:
    commands:
      - cd dist/Angular11Crud
      - ls -la
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - '**/dist/Angular11Crud/*'
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
  # base-directory: 'dist/Angular11Crud/*'
#cache:
  #paths:
    # - paths